import {NgModule} from '@angular/core';
import {
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatOptionModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatTabsModule,
    MatToolbarModule,
    MatTableModule
} from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatChipsModule,
        MatOptionModule,
        MatGridListModule,
        MatProgressBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatDialogModule,
        MatSnackBarModule,
        MatSelectModule,
        MatInputModule,
        MatSidenavModule,
        MatCardModule,
        MatIconModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatTabsModule,
        MatListModule,
        MatTableModule
    ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatChipsModule,
        MatOptionModule,
        MatGridListModule,
        MatProgressBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatDialogModule,
        MatSnackBarModule,
        MatSelectModule,
        MatInputModule,
        MatSidenavModule,
        MatCardModule,
        MatIconModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatTabsModule,
        MatListModule,
        MatTableModule
    ],
})
export class AppMaterialModule {
}
